In [1]:
import yfinance as yf

# Microsoft(MSFT)에 대한 Ticker 객체 생성
msft=yf.Ticker("MSFT")

# Ticker 객체의 정보 출력(.py에서 실행할 때는 print(msft.info)로 사용)
display(msft.info)

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "Microsoft Corporation develops and supports software, services, devices, and solutions worldwide. The company's Productivity and Business Processes segment offers Microsoft 365 Commercial, Enterprise Mobility + Security, Windows Commercial, Power BI, Exchange, SharePoint, Microsoft Teams, Security and Compliance, and Copilot; Microsoft 365 Commercial products, such as Windows Commercial on-premises and Office licensed services; Microsoft 365 Consumer products and cloud services, such as Microsoft 365 Consumer subscriptions, Office licensed on-premises, and other consumer services; LinkedIn; Dynamics products and cloud services, such as Dynamics 365, cloud-based applications, and on-premises ERP and CRM applications. Its Intelligent Cloud segment provides Server products and cloud services, such as Azure and other cloud services, GitHub, Nuance Healthcare, virtual desktop offerings, and other cloud services; Server products, including SQL and Windows Server, Visual Studio and System Center related Client Access Licenses, and other on-premises offerings; Enterprise and partner services, including Enterprise Support and Nuance professional Services, Industry Solutions, Microsoft Partner Network, and Learning Experience. The company's Personal Computing segment provides Windows and Devices, such as Windows OEM licensing and Devices and Surface and PC accessories; Gaming services and solutions, such as Xbox hardware, content, and services, first- and third-party content Xbox Game Pass, subscriptions, and Cloud Gaming, advertising, and other cloud services; search and news advertising services, such as Bing and Copilot, Microsoft News and Edge, and third-party affiliates. It sells its products through OEMs, distributors, and resellers; and online and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.",
 'fullTimeEmployees': 228000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 57,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2024,
   'totalPay': 7869791,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 65,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2024,
   'totalPay': 4755618,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 52,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2024,
   'totalPay': 4704250,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 51,
   'title': 'Executive VP & Chief Commercial Officer',
   'yearBorn': 1973,
   'fiscalYear': 2024,
   'totalPay': 4534974,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Carolina  Dybeck Happe',
   'age': 52,
   'title': 'Executive VP & COO',
   'yearBorn': 1972,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 58,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1966,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Jonathan  Neilson',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hossein  Nowbar',
   'title': 'Chief Legal Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Frank X. Shaw',
   'title': 'Chief Communications Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Takeshi  Numoto',
   'age': 53,
   'title': 'Executive VP & Chief Marketing Officer',
   'yearBorn': 1971,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 9,
 'boardRisk': 5,
 'compensationRisk': 4,
 'shareHolderRightsRisk': 2,
 'overallRisk': 3,
 'governanceEpochDate': 1756684800,
 'compensationAsOfEpochDate': 1735603200,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 501.01,
 'open': 506.51,
 'dayLow': 503.8684,
 'dayHigh': 512.55,
 'regularMarketPreviousClose': 501.01,
 'regularMarketOpen': 506.51,
 'regularMarketDayLow': 503.8684,
 'regularMarketDayHigh': 512.55,
 'dividendRate': 3.32,
 'dividendYield': 0.65,
 'exDividendDate': 1755734400,
 'payoutRatio': 0.2375,
 'fiveYearAvgDividendYield': 0.82,
 'beta': 1.04,
 'trailingPE': 37.30066,
 'forwardPE': 34.107025,
 'volume': 23242411,
 'regularMarketVolume': 23242411,
 'averageVolume': 20392419,
 'averageVolume10days': 19822650,
 'averageDailyVolume10Day': 19822650,
 'bid': 509.81,
 'ask': 510.2,
 'bidSize': 2,
 'askSize': 2,
 'marketCap': 3790173372416,
 'fiftyTwoWeekLow': 344.79,
 'fiftyTwoWeekHigh': 555.45,
 'priceToSalesTrailing12Months': 13.453499,
 'fiftyDayAverage': 510.3924,
 'twoHundredDayAverage': 446.13864,
 'trailingAnnualDividendRate': 3.32,
 'trailingAnnualDividendYield': 0.006626614,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3807790497792,
 'profitMargins': 0.36146,
 'floatShares': 7422239624,
 'sharesOutstanding': 7433169920,
 'sharesShort': 58491994,
 'sharesShortPriorMonth': 52644614,
 'sharesShortPreviousMonthDate': 1753920000,
 'dateShortInterest': 1756425600,
 'sharesPercentSharesOut': 0.007900001,
 'heldPercentInsiders': 0.00067000004,
 'heldPercentInstitutions': 0.74491996,
 'shortRatio': 2.56,
 'shortPercentOfFloat': 0.007900001,
 'impliedSharesOutstanding': 7433169920,
 'bookValue': 46.204,
 'priceToBook': 11.035841,
 'lastFiscalYearEnd': 1751241600,
 'nextFiscalYearEnd': 1782777600,
 'mostRecentQuarter': 1751241600,
 'earningsQuarterlyGrowth': 0.236,
 'netIncomeToCommon': 101831999488,
 'trailingEps': 13.67,
 'forwardEps': 14.95,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 13.516,
 'enterpriseToEbitda': 24.327,
 '52WeekChange': 0.1821301,
 'SandP52WeekChange': 0.16885936,
 'lastDividendValue': 0.83,
 'lastDividendDate': 1755734400,
 'quoteType': 'EQUITY',
 'currentPrice': 509.9,
 'targetHighPrice': 700.0,
 'targetLowPrice': 483.0,
 'targetMeanPrice': 615.3839,
 'targetMedianPrice': 630.0,
 'recommendationMean': 1.26316,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 51,
 'totalCash': 94564999168,
 'totalCashPerShare': 12.722,
 'ebitda': 156528001024,
 'totalDebt': 112184000512,
 'quickRatio': 1.223,
 'currentRatio': 1.353,
 'totalRevenue': 281723994112,
 'debtToEquity': 32.661,
 'revenuePerShare': 37.902,
 'returnOnAssets': 0.14203,
 'returnOnEquity': 0.33280998,
 'grossProfits': 193893007360,
 'freeCashflow': 61070376960,
 'operatingCashflow': 136162000896,
 'earningsGrowth': 0.237,
 'revenueGrowth': 0.181,
 'grossMargins': 0.68824,
 'ebitdaMargins': 0.55561,
 'operatingMargins': 0.44901,
 'financialCurrency': 'USD',
 'symbol': 'MSFT',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'priceEpsCurrentYear': 32.854572,
 'fiftyDayAverageChange': -0.49240112,
 'fiftyDayAverageChangePercent': -0.0009647501,
 'twoHundredDayAverageChange': 63.761353,
 'twoHundredDayAverageChangePercent': 0.14291824,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_21835',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'marketState': 'CLOSED',
 'regularMarketChangePercent': 1.77441,
 'regularMarketPrice': 509.9,
 'corporateActions': [],
 'postMarketTime': 1757721596,
 'regularMarketTime': 1757707201,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 511108200000,
 'postMarketChangePercent': 0.00588327,
 'postMarketPrice': 509.93,
 'postMarketChange': 0.0299988,
 'regularMarketChange': 8.88998,
 'regularMarketDayRange': '503.8684 - 512.55',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 20392419,
 'fiftyTwoWeekLowChange': 165.10999,
 'fiftyTwoWeekLowChangePercent': 0.47887114,
 'fiftyTwoWeekRange': '344.79 - 555.45',
 'fiftyTwoWeekHighChange': -45.55002,
 'fiftyTwoWeekHighChangePercent': -0.08200561,
 'fiftyTwoWeekChangePercent': 18.213009,
 'dividendDate': 1757548800,
 'earningsTimestamp': 1753905600,
 'earningsTimestampStart': 1761768000,
 'earningsTimestampEnd': 1761768000,
 'earningsCallTimestampStart': 1753911000,
 'earningsCallTimestampEnd': 1753911000,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 13.67,
 'epsForward': 14.95,
 'epsCurrentYear': 15.51991,
 'displayName': 'Microsoft',
 'trailingPegRatio': 2.2338}

In [2]:
hist=msft.history(period="5d") # 5일간의 주가 데이터 가져오기
display(hist)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-09-08 00:00:00-04:00,498.109985,501.200012,495.029999,498.200012,16771000,0.0,0.0
2025-09-09 00:00:00-04:00,501.429993,502.250000,497.700012,498.410004,14410500,0.0,0.0
2025-09-10 00:00:00-04:00,502.980011,503.230011,496.720001,500.369995,21611800,0.0,0.0
2025-09-11 00:00:00-04:00,502.250000,503.170013,497.880005,501.010010,18881600,0.0,0.0
2025-09-12 00:00:00-04:00,506.649994,512.549988,503.850006,509.899994,23612600,0.0,0.0

In [3]:
msft.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m         13   43     1     0           0
1    -1m         12   43     1     0           0
2    -2m         12   43     3     0           0
3    -3m         13   40     6     0           0

In [4]:
google=yf.Ticker("GOOGL")
display(google.info)

{'address1': '1600 Amphitheatre Parkway',
 'city': 'Mountain View',
 'state': 'CA',
 'zip': '94043',
 'country': 'United States',
 'phone': '650-253-0000',
 'website': 'https://abc.xyz',
 'industry': 'Internet Content & Information',
 'industryKey': 'internet-content-information',
 'industryDisp': 'Internet Content & Information',
 'sector': 'Communication Services',
 'sectorKey': 'communication-services',
 'sectorDisp': 'Communication Services',
 'longBusinessSummary': 'Alphabet Inc. offers various products and platforms in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America. It operates through Google Services, Google Cloud, and Other Bets segments. The Google Services segment provides products and services, including ads, Android, Chrome, devices, Gmail, Google Drive, Google Maps, Google Photos, Google Play, Search, and YouTube. It is also involved in the sale of apps and in-app purchases and digital content in the Google Play and YouTube; and devices, as well as in the provision of YouTube consumer subscription services. The Google Cloud segment offers AI infrastructure, Vertex AI platform, cybersecurity, data and analytics, and other services; Google Workspace that include cloud-based communication and collaboration tools for enterprises, such as Calendar, Gmail, Docs, Drive, and Meet; and other services for enterprise customers. The Other Bets segment sells healthcare-related and internet services. The company was incorporated in 1998 and is headquartered in Mountain View, California.',
 'fullTimeEmployees': 187103,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Sundar  Pichai',
   'age': 51,
   'title': 'CEO & Director',
   'yearBorn': 1973,
   'fiscalYear': 2024,
   'totalPay': 10319413,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Ruth M. Porat',
   'age': 66,
   'title': 'President & Chief Investment Officer',
   'yearBorn': 1958,
   'fiscalYear': 2024,
   'totalPay': 3023363,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Dr. Lawrence Edward Page II',
   'age': 51,
   'title': 'Co-Founder & Director',
   'yearBorn': 1973,
   'fiscalYear': 2024,
   'totalPay': 1,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sergey  Brin',
   'age': 50,
   'title': 'Co-Founder & Director',
   'yearBorn': 1974,
   'fiscalYear': 2024,
   'totalPay': 1,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Anat  Ashkenazi',
   'age': 51,
   'title': 'Senior VP & CFO',
   'yearBorn': 1973,
   'fiscalYear': 2024,
   'totalPay': 11455556,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. J. Kent Walker',
   'age': 63,
   'title': 'President of Global Affairs, Chief Legal Officer & Company Secretary',
   'yearBorn': 1961,
   'fiscalYear': 2024,
   'totalPay': 3019696,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Philipp  Schindler',
   'age': 53,
   'title': 'Senior Vice President & Chief Business Officer of Google',
   'yearBorn': 1971,
   'fiscalYear': 2024,
   'totalPay': 3051699,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Amie Thuener O'Toole",
   'age': 49,
   'title': 'Corporate Controller, Chief Accounting Officer & VP',
   'yearBorn': 1975,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Ellen  West',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Fiona Clare Cicconi',
   'age': 58,
   'title': 'Chief People Officer',
   'yearBorn': 1966,
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 9,
 'compensationRisk': 10,
 'shareHolderRightsRisk': 10,
 'overallRisk': 10,
 'governanceEpochDate': 1756684800,
 'compensationAsOfEpochDate': 1735603200,
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 240.37,
 'open': 240.675,
 'dayLow': 238.0,
 'dayHigh': 242.075,
 'regularMarketPreviousClose': 240.37,
 'regularMarketOpen': 240.675,
 'regularMarketDayLow': 238.0,
 'regularMarketDayHigh': 242.075,
 'dividendRate': 0.84,
 'dividendYield': 0.35,
 'exDividendDate': 1757289600,
 'payoutRatio': 0.0864,
 'beta': 1.011,
 'trailingPE': 25.644302,
 'forwardPE': 26.875,
 'volume': 26497167,
 'regularMarketVolume': 26497167,
 'averageVolume': 38444761,
 'averageVolume10days': 45189860,
 'averageDailyVolume10Day': 45189860,
 'bid': 240.62,
 'ask': 240.95,
 'bidSize': 4,
 'askSize': 4,
 'marketCap': 2915389669376,
 'fiftyTwoWeekLow': 140.53,
 'fiftyTwoWeekHigh': 242.25,
 'priceToSalesTrailing12Months': 7.849751,
 'fiftyDayAverage': 201.2256,
 'twoHundredDayAverage': 181.0402,
 'trailingAnnualDividendRate': 1.01,
 'trailingAnnualDividendYield': 0.0042018555,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 2858755293184,
 'profitMargins': 0.31118,
 'floatShares': 10836465880,
 'sharesOutstanding': 5816999936,
 'sharesShort': 55471936,
 'sharesShortPriorMonth': 57377636,
 'sharesShortPreviousMonthDate': 1753920000,
 'dateShortInterest': 1756425600,
 'sharesPercentSharesOut': 0.0046,
 'heldPercentInsiders': 0.0025799999,
 'heldPercentInstitutions': 0.80907,
 'shortRatio': 1.79,
 'shortPercentOfFloat': 0.0095,
 'impliedSharesOutstanding': 12107100160,
 'bookValue': 29.983,
 'priceToBook': 8.031218,
 'lastFiscalYearEnd': 1735603200,
 'nextFiscalYearEnd': 1767139200,
 'mostRecentQuarter': 1751241600,
 'earningsQuarterlyGrowth': 0.194,
 'netIncomeToCommon': 115572998144,
 'trailingEps': 9.39,
 'forwardEps': 8.96,
 'lastSplitFactor': '20:1',
 'lastSplitDate': 1658102400,
 'enterpriseToRevenue': 7.697,
 'enterpriseToEbitda': 20.298,
 '52WeekChange': 0.5234721,
 'SandP52WeekChange': 0.16885936,
 'lastDividendValue': 0.21,
 'lastDividendDate': 1757289600,
 'quoteType': 'EQUITY',
 'currentPrice': 240.8,
 'targetHighPrice': 300.0,
 'targetLowPrice': 185.0,
 'targetMeanPrice': 232.56,
 'targetMedianPrice': 227.5,
 'recommendationMean': 1.55385,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 50,
 'totalCash': 95147999232,
 'totalCashPerShare': 7.867,
 'ebitda': 140840992768,
 'totalDebt': 41668001792,
 'quickRatio': 1.72,
 'currentRatio': 1.904,
 'totalRevenue': 371399000064,
 'debtToEquity': 11.481,
 'revenuePerShare': 30.428,
 'returnOnAssets': 0.16792,
 'returnOnEquity': 0.34829,
 'grossProfits': 218911997952,
 'freeCashflow': 49786499072,
 'operatingCashflow': 133707997184,
 'earningsGrowth': 0.223,
 'revenueGrowth': 0.138,
 'grossMargins': 0.58943003,
 'ebitdaMargins': 0.37922,
 'operatingMargins': 0.32429,
 'financialCurrency': 'USD',
 'symbol': 'GOOGL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'shortName': 'Alphabet Inc.',
 'longName': 'Alphabet Inc.',
 'regularMarketChangePercent': 0.178894,
 'regularMarketPrice': 240.8,
 'marketState': 'CLOSED',
 'postMarketChangePercent': -0.120435,
 'postMarketPrice': 240.51,
 'postMarketChange': -0.290009,
 'regularMarketChange': 0.430008,
 'regularMarketDayRange': '238.0 - 242.075',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 38444761,
 'fiftyTwoWeekLowChange': 100.270004,
 'fiftyTwoWeekLowChangePercent': 0.71351314,
 'fiftyTwoWeekRange': '140.53 - 242.25',
 'fiftyTwoWeekHighChange': -1.449997,
 'fiftyTwoWeekHighChangePercent': -0.0059855394,
 'fiftyTwoWeekChangePercent': 52.347206,
 'dividendDate': 1757894400,
 'earningsTimestamp': 1753300800,
 'earningsTimestampStart': 1753300800,
 'earningsTimestampEnd': 1753300800,
 'earningsCallTimestampStart': 1753302600,
 'earningsCallTimestampEnd': 1753302600,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 9.39,
 'epsForward': 8.96,
 'epsCurrentYear': 9.96132,
 'priceEpsCurrentYear': 24.173504,
 'fiftyDayAverageChange': 39.5744,
 'fiftyDayAverageChangePercent': 0.19666684,
 'twoHundredDayAverageChange': 59.759796,
 'twoHundredDayAverageChangePercent': 0.3300913,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.6 - Buy',
 'cryptoTradeable': False,
 'corporateActions': [],
 'postMarketTime': 1757721595,
 'regularMarketTime': 1757707200,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_29096',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 1092922200000,
 'trailingPegRatio': 1.6381}

In [5]:
hist2=google.history(period="5d")
display(hist2)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-09-08 00:00:00-04:00,235.470001,238.130005,233.669998,234.039993,32474700,0.21,0.0
2025-09-09 00:00:00-04:00,234.169998,240.470001,233.229996,239.630005,38061000,0.00,0.0
2025-09-10 00:00:00-04:00,238.899994,241.660004,237.850006,239.169998,35141100,0.00,0.0
2025-09-11 00:00:00-04:00,239.880005,242.250000,236.250000,240.369995,30599300,0.00,0.0
2025-09-12 00:00:00-04:00,240.369995,242.080002,238.000000,240.800003,26761900,0.00,0.0

In [6]:
google.recommendations

  period  strongBuy  buy  hold  sell  strongSell
0     0m         12   41    12     0           0
1    -1m         13   41    11     0           0
2    -2m         13   43    12     0           0
3    -3m         15   42    12     0           0